version: '3.7'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: istory
      MYSQL_USER: pinetree
      MYSQL_PASSWORD: admin123
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

